name: Build & Push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

env:
  CR_REGISTRY: crpiop5kci1440r661pk     # your YCR registry id
  CR_REPOSITORY: nginx                 # your repo name in YCR
  DOCKERFILE: ./nginx/Dockerfile
  CONTEXT: .                            # path to build context
  # Tag scheme: latest + short SHA
  TAGS_SIMPLE: latest,${{ github.sha }}

jobs:
  ycr:
    name: Docker Hub
    runs-on: ubuntu-latest
    environment: prod 
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # sanity check: fail fast if the secret is missing/empty
      - name: Verify YC_SA_ID is set
        run: test -n "${{ secrets.YC_SA_ID }}" || { echo "YC_SA_ID is empty or undefined"; exit 1; }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to YCR
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-id: ${{ secrets.YC_SA_ID }}

      - name: Extract metadata (labels, tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
